--liquibase formatted sql for postgres

--changeset wolfbertfx:1
CREATE TABLE assets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id INTEGER      NOT NULL,
    status_id     INTEGER      NOT NULL,
    version       BIGINT       NOT NULL DEFAULT 0,
    last_updated  TIMESTAMPTZ,
    CONSTRAINT ux_assets_instrument UNIQUE (instrument_id)
);
--rollback DROP TABLE assets;

--changeset wolfbertfx:2
CREATE TABLE venue_sessions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id      INTEGER      NOT NULL,
    day_of_week   SMALLINT     NOT NULL,
    phase_id      SMALLINT     NOT NULL,
    open_time     TIME         NOT NULL,
    close_time    TIME         NOT NULL,
    version       BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ux_venue_session UNIQUE (venue_id, day_of_week, phase_id)
);
--rollback DROP TABLE venue_sessions;

--changeset wolfbertfx:3
CREATE TABLE calendar_exceptions (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id             INTEGER      NOT NULL,
    start_date           DATE         NOT NULL,
    end_date             DATE         NOT NULL,
    instrument_id        INTEGER,
    instrument_type_id   INTEGER,
    exception_type       VARCHAR(20)  NOT NULL,
    description          VARCHAR(255),
    version              BIGINT       NOT NULL DEFAULT 0
);
CREATE INDEX ix_cal_exc_venue_dates ON calendar_exceptions (venue_id, start_date, end_date);
--rollback DROP TABLE calendar_exceptions;