--liquibase formatted sql for postgres

--changeset wolfbertfx:1
CREATE TABLE assets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id INTEGER      NOT NULL,
    status_id     INTEGER      NOT NULL,
    version       BIGINT       NOT NULL DEFAULT 0,
    last_updated  TIMESTAMPTZ,
    CONSTRAINT ux_assets_instrument UNIQUE (instrument_id)
);
--rollback DROP TABLE assets;
