# Swagger Configuration
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Houston Control API
quarkus.smallrye-openapi.info-description=ля ля ля

# Postgres Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/control
quarkus.datasource.username=postgres
quarkus.datasource.password=secretpassword
quarkus.datasource.jdbc.initial-size=1

# Liquibase Configuration
quarkus.liquibase.change-log=liquibase/master.xml
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.validate-on-migrate=true